
service: serverless-appsync-backend

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-central-1

functions:
  hello:
    handler: handler.hello

# you can add CloudFormation resource templates here
resources:
  Resources:
    ${file(resources.yml)}

